### ISSUE TITLE
State update warning

### ISSUE THREAD

**Issue by kiranvj** [lamyfarai/react-typing-effect#1]
I am getting the below warning sometimes. not consistent. This happens when I change pages via react-router.

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
>     in TypingEffect (at Hero/index.jsx:14)

This is line:14

```
<ReactTypingEffect
                  text={musicTypes} 
                  speed={100}
                  eraseDelay={1000}
                  className="ml-2 type-text text-red"
                  />
```

**Comment by lamyfarai** [comment]
Fixed
